HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.22227/1997-0935.2023.1.102-115 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f56916a71d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.15700/saje.v42n4a2096 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f56916a6e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1039/c9nj01257e (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5691827550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.3390/genes13091521 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa60f63cc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1063/1.1486445 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5afe45fe90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1021/cm011675j (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766de90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/01443579610125787 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/01437730110380183 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1149/1.1392654 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/02651330010339905 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/14691930010371618 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1021/ic020157n (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1103/physreve.65.061511 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1093/intqhc/12.4.339 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766e290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1128/aac.46.8.2588-2594.2002 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766ed50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/14691930010359243 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766ee90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/09696479510086208 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766f110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1108/09684879710156513 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766f250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1163/156856102760070385 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5af766f390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1017/s0950017098000257 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe5181a6e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1007/bfb0037168 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d304d9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.18125/2154kqg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d301e350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1163/imbo-book-8_9 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d30335d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1016/s0370-2693(97)00376-6 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d3029290>, 'Connection to api.crossref.org timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1016/j.amepre.2010.01.015 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d30285d0>, 'Connection to api.crossref.org timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1002/maco.19670180104 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d3010350>, 'Connection to api.crossref.org timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1038/nsmb0210-141 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_DECODE_ERROR] tlsv1 alert decode error (_ssl.c:1002)')))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1103/physreva.52.197 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d301fb90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1145/3532211 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d30c7310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1007/s13197-013-0930-1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d30c20d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1139/cjfr-2021-0145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d30550d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1109/iciteed.2015.7409003 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d304ee90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1088/1742-6596/324/1/012022 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d3053010>, 'Connection to api.crossref.org timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1016/s0002-9378(12)91812-8 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d2ffe290>, 'Connection to api.crossref.org timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1017/s0898030600006758 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb6d301dd50>, 'Connection to api.crossref.org timed out. (connect timeout=None)'))
